apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-secrets-store
  template:
    metadata:
      labels:
        app: csi-secrets-store
    spec:
      serviceAccountName: secrets-store-csi-driver
      containers:
        - name: driver
          image: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:latest
          imagePullPolicy: Always
          args:
            - "--endpoint=unix:///var/lib/kubelet/plugins/secrets-store.csi.k8s.io/csi.sock"
            - "--provider-volume=/etc/kubernetes/secrets-store-csi-providers"
          env:
            - name: TZ
              value: UTC
          volumeMounts:
            - name: providervol
              mountPath: "/etc/kubernetes/secrets-store-csi-providers"
            - name: mountpoint-dir
              mountPath: "/var/lib/kubelet/pods"
              mountPropagation: HostToContainer
            - name: registration-dir
              mountPath: "/registration"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: "/var/lib/kubelet/pods"
            type: Directory
        - name: registration-dir
          hostPath:
            path: "/var/lib/kubelet/plugins_registry"
            type: Directory 