apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .ProjectName }}-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
          - path: host
            objectAlias: db-host
          - path: port
            objectAlias: db-port
          - path: database
            objectAlias: db-name
      - objectName: "{{ .ProjectName }}-cognito-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: user_pool_id
            objectAlias: cognito-user-pool-id
          - path: client_id
            objectAlias: cognito-client-id
          - path: client_secret
            objectAlias: cognito-client-secret
          - path: domain
            objectAlias: cognito-domain 