apiVersion: v1
kind: Namespace
metadata:
  name: aidocs-assistant
  labels:
    name: aidocs-assistant
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aidocs-assistant-quota
  namespace: aidocs-assistant
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "5" 