apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/csi-driver.yaml
  - namespaces/namespace.yaml
  - rbac/rbac.yaml
  - storage/storage.yaml
  - monitoring/monitoring.yaml

commonLabels:
  app: aidocs-assistant
  managed-by: kustomize 