apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./resources/secrets-provider-class.yaml

namespace: aidocs-assistant

commonLabels:
  environment: dev
  app: aidocs-assistant

patchesStrategicMerge:
  - patches/resource-quota-patch.yaml 